### ISSUE TITLE
Broken support for Selenium Chrome Webdriver

### ISSUE THREAD

**Issue by steven-cutting** [percy/percy-python-selenium#2]
In the [`envInfo`](https://github.com/percy/percy-python-selenium/blob/master/percy/snapshot.py#L41) function it assumes that a `browserVersion` key 
 is available on the `webdriver.capabilities` dict. When using the Chrome webdriver `browserVersion` is not available.

While the code does use `dict.get` to, I assume, avoid a KeyError exception. It does not properly handle the case in which `dict.get` does not find the requested key and returns the default `None`. What ends up happening when using Chrome is you get a vague error from the code trying to concatenate `None` to a string. Would have been better to just use the standard dict get item method (`dict[key]`) and get the key error.

It would be nice if you could fix this specific issue, but to help find/avoid other issues it would be good if you could test against the chrome webdriver in addition to firefox.

**Comment by Robdel12** [comment]
Hey @steven-cutting thanks for reporting! Could you tell me which version of Chromedriver you're seeing this issue with? We're using [Chromedriver in the example app without any issues](https://github.com/percy/example-percy-python-selenium/blob/master/tests/todo.py#L5-L12) & the [Webdriver spec shows `browserVersion` apart of `capabilities`](https://www.w3.org/TR/webdriver/#capabilities) (though, it could be unimplemented in older versions).

**Comment by Robdel12** [comment]
Going to close this out, feel free to comment back with more info 👍
